packages:
  - '.papi/descriptors'
allowBuilds:
  bufferutil: false
  esbuild: false
  sharp: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@talismn/*'
overrides:
  'write-package>deepmerge-ts': 8.0.0
  'ws@>=8.0.0 <8.21.0': ^8.21.0
  'lint-staged>yaml': ^2.8.3
