export const isBlacklistedRpcUrl = (url: string): boolean => BLACKLISTED_HOSTS.includes(new URL(url).host)

export const isNotBlacklistedRpcUrl = (url: string): boolean => !isBlacklistedRpcUrl(url)

// fill with RPCs that are flagged by antiviruses, or that causes any other issue
// works for both wss and http rpcs
const BLACKLISTED_RPC_URLS = [
  'https://mainnet.openpiece.io',
  'https://rpc2.mix-blockchain.org:8647',
  'https://mainnet.openpiece.io/ ',
  'https://core.poa.network',
  'https://devnet.web3games.org/evm',
  'https://rpc.public-0138.defi-oracle.io',
  'https://node.mainnet.lightstreams.io',
  'https://rpc.swapdex.network',
  'https://rpcurl.mainnet.plgchain.com',
  'https://mainnet.hashio.io/api',
  'https://arrakis.gorengine.com/own',
  'https://node.cheapeth.org/rpc',
  'https://rpc.zkevm.thefirechain.com',
  'https://mainnet.rpc1.thefirechain.com',
  'https://rpc.softnote.com',
  'https://rpc.luckynetwork.org',
  'https://test.dostchain.com',
  'https://mainnet.zakumi.io',
  'https://rpc.rikscan.com',
  'https://dataseed1.btachain.com',
  'https://rpc.dev.publicmint.io:8545',
  'https://market.bigsb.io',
  'https://prod-forge.prod.findora.org:8545',
  'https://rpc.empirenetwork.io',
  'https://rpc1.phi.network',
  'https://rpc.chain.nexi.technology',
  'https://rpcurl.mainnet.plgchain.plinga.technology',
  'https://chain.nexilix.com',
  'https://node-api.uptn.io/v1/ext/rpc',
  'https://rpc-mainnet.pepenetwork.io',
  'https://rpcpc1-ga.agung.peag.network',
  'https://rpc.astranaut.io',
  'https://rpc1.astranaut.io',
  'https://sanrchain-node.santiment.net',
  'https://gateway.opn.network/node/ext/bc/2VsZe',
  'https://mainnet-rpc.satoshichain.io',
  'https://rpc.autobahn.network',
  'https://api.electroneum.com',
  'https://mainnet.genesyscode.io',
  'https://proxy.thinkiumrpc.net',
  'https://rpc.test.taiko.xyz',
  'https://rpc.l3test.taiko.xyz',
  'https://jellie-rpc.twala.io',
  'https://mainnet.kekchain.com',
  'https://chain.deptofgood.com',
  'https://net.iolite.io',
  'https://rpc.auxilium.global',
  'https://devnet.gather.network',
  'https://rpc.raptorchain.io/web3',
  'https://23.92.21.121:8545',
  'https://mainnet.ipdc.io',
  'https://wallrpc.pirl.io',
  'https://rpc2.phi.network',
  'https://proxy.thinkiumrpc.net/',
  'https://node.sirius.lightstreams.io',
  'https://node.atoshi.io',
  'https://rpc.testnet.dogechain.dog',
  'https://layer1test.decentrabone.com',
  'https://subnets.avax.network/portal-fantasy/testnet/rpc',
  'https://rpc.atheios.org',
  'https://bombchain-testnet.ankr.com/bas_full_rpc_1',
  'https://ngeth.testnet.n3.nahmii.io',
  'https://node-api.alp.uptn.io/v1/ext/rpc',
  'https://evm-rpc.testnet.teleport.network',
  'https://evm.klyntarscan.org',
  'https://evm.klyntar.org',
  'https://blocktonscan.com',
  'https://mainnet.berylbit.io',
  'https://data-aws-testnet.imperiumchain.com',
  'https://data-aws-mainnet.imperiumchain.com',
  'https://data-aws2-testnet.imperiumchain.com',
  'https://data-aws2-mainnet.imperiumchain.com',
  'https://smartbch.devops.cash',
  'https://betaenv.singularity.gold:18545',
  'https://gateway.opn.network/node/ext/bc/2VsZe5DstWw2bfgdx3YbjKcMsJnNDjni95sZorBEdk9L9Qr9Fr/rpc',
  'https://api.testnet-dev.trust.one',
  'https://rpc.condrieu.ethdevops.io',
  'https://testnet.rpc.uschain.network/',
  'https://rpc-devnet-algorand-rollup.a1.milkomeda.com/',
  'https://sparta-rpc.polis.tech/',
  'https://testnet.kekchain.com/',
  'https://rpc.testnet.fastexchain.com/',
  'https://weelinknode1c.gw002.oneitfarm.com/',
  'https://rpc.zhejiang.ethpandaops.io/',
  'https://testnet-rpc.exlscan.com/',
  'https://toys.joys.cash/',
  'https://test.doschain.com/jsonrpc',
  'https://rpc.dexilla.com',
  'https://rpc.xerom.org',
  'https://rpc.hydradx.cloud',
  'wss://rpc.hydradx.cloud',
].map((url) => url.replace(/\/$/, ''))

const BLACKLISTED_HOSTS = BLACKLISTED_RPC_URLS.map((url) => new URL(url).host)
