name: Chaindata Validate

on:
  push:
  pull_request:

concurrency:
  # only run 1 job per branch/pr/etc at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validate:
    name: "Validate chaindata YAML format & schema"
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate YAML format & schema
        run: pnpm validate
