name: Validation

on:
  push:
    branches: [v3, main]
  pull_request:
    branches: [v3, main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - run: yarn --immutable

      - run: yarn ajv --spec=draft2020 -s schemas/json/chaindata.json -d chaindata.json -d testnets-chaindata.json
      - run: yarn ajv --spec=draft2020  -s schemas/json/evm-networks.json -d evm-networks.json
      - run: yarn ajv --spec=draft2020 -s schemas/json/tokens.json -d tokens.json
      - run: yarn ajv --spec=draft2020 -s schemas/json/ids.json -d tokens-buyable.json
